name: Third workflow in Lab 9
run-name: ${{ github.actor }} triggered workflow on ${{ github.event_name }} on branch ${{ github.ref_name }}
on:
 pull_request:
  branches: 
      - bugfix/*
      - feature/*
 push:
  branches: main
jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: List all files
        run: ls -alh
      - name: printing readme
        run: cat README.md

